Misc installer fixes
* Add a warning to fstab.
* Make autologin handling dependant on the installed display manager.
* Make Blueman prompt only display if the desktop environment is Xfce.

diff --git a/livecd-installer b/livecd-installer
--- a/livecd-installer
+++ b/livecd-installer
@@ -16,7 +16,7 @@
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
 # Set version (to be incremented on each update/commit).
-VER=18
+VER=27
 
 # Invocation and header.
 inv="$(basename "$0")"
@@ -501,7 +501,12 @@ begin_installation() {
   # Remove live system features.
   userdel -R "$mountdir" -rf massos &>>"$logfile"
   groupdel -R "$mountdir" -f autologin &>>"$logfile"
-  mv "$mountdir"/etc/lightdm/lightdm.conf.orig "$mountdir"/etc/lightdm/lightdm.conf
+  if [ -f "$mountdir"/etc/lightdm/lightdm.conf.orig ]; then
+    mv "$mountdir"/etc/lightdm/lightdm.conf{.orig,}
+  fi
+  if [ -f "$mountdir"/etc/sddm.conf.d/autologin.conf ]; then
+    rm -f "$mountdir"/etc/sddm.conf.d/autologin.conf
+  fi
   rm -f "$mountdir"/etc/polkit-1/rules.d/49-live.rules
   rm -f "$mountdir"/etc/sudoers.d/live
   rm -f "$mountdir"/usr/bin/livecd-installer
@@ -515,6 +520,7 @@ begin_installation() {
     swapuuid="$(blkid -o value -s UUID "$swappar")"
   fi
   echo "# Automatically generated by MassOS installer." > "$mountdir"/etc/fstab
+  echo "# WARNING: ERRORS IN THIS FILE CAN PREVENT BOOTING!" >> "$mountdir"/etc/fstab
   echo "UUID=$rootuuid / $(blkid -o value -s TYPE "$rootpar") defaults 1 1" >> "$mountdir"/etc/fstab
   if [ "$efisys" = "y" ]; then
     echo "UUID=$efiuuid /boot/efi vfat umask=0077 0 1" >> "$mountdir"/etc/fstab
@@ -1673,13 +1679,15 @@ user_setup() {
     main_menu
     exit
   fi
-  # Blueman.
-  prompt "Bluetooth" "If your system supports Bluetooth, the Blueman utility \
-  and applet can help you graphically manage it. Would you like Blueman to be \
-  autostarted on login?"
-  if [ $? -eq 0 ]; then
-    cp -af "$mountdir"/usr/share/blueman/autostart.desktop \
-    "$mountdir"/etc/xdg/autostart/blueman.desktop
+  # Blueman (Xfce only).
+  if [ -e "$mountdir"/usr/share/xsessions/xfce.desktop ]; then
+    prompt "Bluetooth" "If your system supports Bluetooth, the Blueman tool \
+    and applet can help you graphically manage it. Would you like Blueman to \
+    autostart on login?"
+    if [ $? -eq 0 ]; then
+      cp -af "$mountdir"/usr/share/blueman/autostart.desktop \
+      "$mountdir"/etc/xdg/autostart/blueman.desktop
+    fi
   fi
   # Generate the initramfs.
   installation_stage=5
